import { IConfiguration } from "../typings";

export const defaultConfiguration: IConfiguration = {
    chatServer: '/botman',
    frameEndpoint: '/botman/chat',
    timeFormat: 'HH:MM',
    dateTimeFormat: 'm/d/yy HH:MM',
    title: "Comment puis-je t'aider ?",
    cookieValidInDays: 1,
    introMessage: '',
    introTitle: "Chatbot TPF",
    introPara: "Je suis la pour vous aider à trouver la réponse à vos questions! Alors demander-moi ce que vous voulez! Ecrivez votre message ci-dessous et trouvons ensemble ce qu'il vous faut.",
    placeholderText: 'Écrivez un message...',
    displayMessageTime: true,
    sendWidgetOpenedEvent: false,
    widgetOpenedEventData: '',
    mainColor: '#990033',
    headerTextColor: '#fff',
    bubbleBackground: '#990033',
    bubbleAvatarUrl: '',
    desktopHeight: 450,
    desktopWidth: 370,
    mobileHeight: '100%',
    mobileWidth: '300px',
    videoHeight: 160,
    aboutLink: 'https://botman.io',
    aboutText: '',
    chatId: '',
    userId: '',
    alwaysUseFloatingButton: false,
    useEcho: false,
    echoChannel: (userId: string) => '',
    echoConfiguration: {},
    echoEventName: '.message.created',
    echoChannelType: 'private'
};
